version: '3'

services:
  postgres:
    build: .
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    networks:
      - internal

networks:
  internal:
    driver: bridge
